import { PublicKey } from "@solana/web3.js"
import { SYSTEM_PROGRAM_ADDRESS_STRING } from '/src/assets/globalStates/AnchorPrograms.vue'

const DAI_TOKEN_MINT_ADDRESS_MAINNET = "EjmyN6qEC1Tf1JxiG1ae7UTJhUxSwk1TCWNWqxWV4J6o"
const USDC_TOKEN_MINT_ADDRESS_MAINNET = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
const SOL_TOKEN_MINT_ADDRESS_MAINNET = "So11111111111111111111111111111111111111112"
const WETH_TOKEN_MINT_ADDRESS_MAINNET = "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"
const WBTC_TOKEN_MINT_ADDRESS_MAINNET = "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"

const USDC_TOKEN_MINT_ADDRESS_DEVNET = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
const SOL_TOKEN_MINT_ADDRESS_DEVNET = "So11111111111111111111111111111111111111112"

const HODL_DAI_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const HODL_USDC_ASSOCIATED_TOKEN_ADDRESS_MAINNET = "CNJ2Jb4dMWF8TsMEKsqdaJUkCMnY8AKz5gr9GDjN9cQB"
const HODL_SOL_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const HODL_WETH_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const HODL_WBTC_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING

const HODL_DAI_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const HODL_USDC_ASSOCIATED_TOKEN_ADDRESS_DEVNET = "CNJ2Jb4dMWF8TsMEKsqdaJUkCMnY8AKz5gr9GDjN9cQB"
const HODL_SOL_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const HODL_WETH_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const HODL_WBTC_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING

const SINGLE_PAYER_DAI_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const SINGLE_PAYER_USDC_ASSOCIATED_TOKEN_ADDRESS_MAINNET = "FLSfaiYMwfbJhfzsmSvSjCGQE9CGfbXcnG7o9ZTz3F7i"
const SINGLE_PAYER_SOL_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const SINGLE_PAYER_WETH_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const SINGLE_PAYER_WBTC_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING

const SINGLE_PAYER_DAI_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const SINGLE_PAYER_USDC_ASSOCIATED_TOKEN_ADDRESS_DEVNET = "FLSfaiYMwfbJhfzsmSvSjCGQE9CGfbXcnG7o9ZTz3F7i"
const SINGLE_PAYER_SOL_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const SINGLE_PAYER_WETH_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const SINGLE_PAYER_WBTC_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING

const TOKEN_RESERVE_DAI_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const TOKEN_RESERVE_USDC_ASSOCIATED_TOKEN_ADDRESS_MAINNET = "5CoRP7HxkZJG52QmGQv6tRKutsfxPE9k12aKoPD7tR65"
const TOKEN_RESERVE_SOL_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const TOKEN_RESERVE_WETH_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING
const TOKEN_RESERVE_WBTC_ASSOCIATED_TOKEN_ADDRESS_MAINNET = SYSTEM_PROGRAM_ADDRESS_STRING

const TOKEN_RESERVE_DAI_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const TOKEN_RESERVE_USDC_ASSOCIATED_TOKEN_ADDRESS_DEVNET = "5gLXj6DpoKjbL76vgRc851KmBz6Aq7kVNLAnCX6Aa3NC"
const TOKEN_RESERVE_SOL_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const TOKEN_RESERVE_WETH_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING
const TOKEN_RESERVE_WBTC_ASSOCIATED_TOKEN_ADDRESS_DEVNET = SYSTEM_PROGRAM_ADDRESS_STRING

export const tokenAddressStringsMainNet = 
{
    daiTokenMintAddress: DAI_TOKEN_MINT_ADDRESS_MAINNET,
    usdcTokenMintAddress: USDC_TOKEN_MINT_ADDRESS_MAINNET,
    solTokenMintAddress: SOL_TOKEN_MINT_ADDRESS_MAINNET,
    wethTokenMintAddress: WETH_TOKEN_MINT_ADDRESS_MAINNET,
    wbtcTokenMintAddress: WBTC_TOKEN_MINT_ADDRESS_MAINNET
}

export const tokenAddressStringsDevNet = 
{
    daiTokenMintAddress: DAI_TOKEN_MINT_ADDRESS_MAINNET,
    usdcTokenMintAddress: USDC_TOKEN_MINT_ADDRESS_DEVNET,
    solTokenMintAddress: SOL_TOKEN_MINT_ADDRESS_DEVNET,
    wethTokenMintAddress: WETH_TOKEN_MINT_ADDRESS_MAINNET,
    wbtcTokenMintAddress: WBTC_TOKEN_MINT_ADDRESS_MAINNET
}

export const tokenAddressKeysMainNet = 
{
    daiTokenMintAddress: new PublicKey(DAI_TOKEN_MINT_ADDRESS_MAINNET),
    usdcTokenMintAddress: new PublicKey(USDC_TOKEN_MINT_ADDRESS_MAINNET),
    solTokenMintAddress: new PublicKey(SOL_TOKEN_MINT_ADDRESS_MAINNET),
    wethTokenMintAddress: new PublicKey(WETH_TOKEN_MINT_ADDRESS_MAINNET),
    wbtcTokenMintAddress: new PublicKey(WBTC_TOKEN_MINT_ADDRESS_MAINNET)
}

export const tokenAddressKeysDevNet = 
{
    daiTokenMintAddress: new PublicKey(DAI_TOKEN_MINT_ADDRESS_MAINNET),
    usdcTokenMintAddress: new PublicKey(USDC_TOKEN_MINT_ADDRESS_DEVNET),
    solTokenMintAddress: new PublicKey(SOL_TOKEN_MINT_ADDRESS_DEVNET),
    wethTokenMintAddress: new PublicKey(WETH_TOKEN_MINT_ADDRESS_MAINNET),
    wbtcTokenMintAddress: new PublicKey(WBTC_TOKEN_MINT_ADDRESS_MAINNET)
}

export const hodlAssociatedTokenAddressKeysMainNet = 
{
    daiATA: new PublicKey(HODL_DAI_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    usdcATA: new PublicKey(HODL_USDC_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    solATA: new PublicKey(HODL_SOL_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    wethATA: new PublicKey(HODL_WETH_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    wbtcATA: new PublicKey(HODL_WBTC_ASSOCIATED_TOKEN_ADDRESS_MAINNET)
}

export const hodlAssociatedTokenAddressKeysDevNet = 
{
    daiATA: new PublicKey(HODL_DAI_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    usdcATA: new PublicKey(HODL_USDC_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    solATA: new PublicKey(HODL_SOL_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    wethATA: new PublicKey(HODL_WETH_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    wbtcATA: new PublicKey(HODL_WBTC_ASSOCIATED_TOKEN_ADDRESS_DEVNET)
}

export const singlePayerAssociatedTokenAddressKeysMainNet = 
{
    daiATA: new PublicKey(SINGLE_PAYER_DAI_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    usdcATA: new PublicKey(SINGLE_PAYER_USDC_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    solATA: new PublicKey(SINGLE_PAYER_SOL_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    wethATA: new PublicKey(SINGLE_PAYER_WETH_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    wbtcATA: new PublicKey(SINGLE_PAYER_WBTC_ASSOCIATED_TOKEN_ADDRESS_MAINNET)
}

export const singlePayerAssociatedTokenAddressKeysDevNet = 
{
    daiATA: new PublicKey(SINGLE_PAYER_DAI_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    usdcATA: new PublicKey(SINGLE_PAYER_USDC_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    solATA: new PublicKey(SINGLE_PAYER_SOL_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    wethATA: new PublicKey(SINGLE_PAYER_WETH_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    wbtcATA: new PublicKey(SINGLE_PAYER_WBTC_ASSOCIATED_TOKEN_ADDRESS_DEVNET)
}

export const tokenReserveAssociatedTokenAddressKeysMainNet = 
{
    daiATA: new PublicKey(TOKEN_RESERVE_DAI_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    usdcATA: new PublicKey(TOKEN_RESERVE_USDC_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    solATA: new PublicKey(TOKEN_RESERVE_SOL_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    wethATA: new PublicKey(TOKEN_RESERVE_WETH_ASSOCIATED_TOKEN_ADDRESS_MAINNET),
    wbtcATA: new PublicKey(TOKEN_RESERVE_WBTC_ASSOCIATED_TOKEN_ADDRESS_MAINNET)
}

export const tokenReserveAssociatedTokenAddressKeysDevNet = 
{
    daiATA: new PublicKey(TOKEN_RESERVE_DAI_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    usdcATA: new PublicKey(TOKEN_RESERVE_USDC_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    solATA: new PublicKey(TOKEN_RESERVE_SOL_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    wethATA: new PublicKey(TOKEN_RESERVE_WETH_ASSOCIATED_TOKEN_ADDRESS_DEVNET),
    wbtcATA: new PublicKey(TOKEN_RESERVE_WBTC_ASSOCIATED_TOKEN_ADDRESS_DEVNET)
}

export const tokenDecimalHashMap: Map<string, number> = new Map(
[
    //Key: Token Mint Address, Value: Token Decimal Amount
    [tokenAddressStringsMainNet.daiTokenMintAddress, 8],
    [tokenAddressStringsMainNet.usdcTokenMintAddress,6],
    [tokenAddressStringsDevNet.usdcTokenMintAddress,6],
    [tokenAddressStringsMainNet.solTokenMintAddress, 9],
    [tokenAddressStringsMainNet.wethTokenMintAddress,8],
    [tokenAddressStringsMainNet.wbtcTokenMintAddress,8]
])