import { PublicKey } from "@solana/web3.js"

const DAI_TOKEN_MINT_ADDRESS_MAINNET = "EjmyN6qEC1Tf1JxiG1ae7UTJhUxSwk1TCWNWqxWV4J6o"
const USDC_TOKEN_MINT_ADDRESS_MAINNET = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
const SOL_TOKEN_MINT_ADDRESS_MAINNET = "So11111111111111111111111111111111111111112"
const WETH_TOKEN_MINT_ADDRESS_MAINNET = "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"
const WBTC_TOKEN_MINT_ADDRESS_MAINNET = "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"

const USDC_TOKEN_MINT_ADDRESS_DEVNET = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
const SOL_TOKEN_MINT_ADDRESS_DEVNET = "So11111111111111111111111111111111111111112"

export const tokenAddressStringsMainNet = 
{
    DAITokenMintAddress: DAI_TOKEN_MINT_ADDRESS_MAINNET,
    USDCTokenMintAddress: USDC_TOKEN_MINT_ADDRESS_MAINNET,
    SOLTokenMintAddress: SOL_TOKEN_MINT_ADDRESS_MAINNET,
    WETHTokenMintAddress: WETH_TOKEN_MINT_ADDRESS_MAINNET,
    WBTCTokenMintAddress: WBTC_TOKEN_MINT_ADDRESS_MAINNET
}

export const tokenAddressStringsDevNet = 
{
    DAITokenMintAddress: DAI_TOKEN_MINT_ADDRESS_MAINNET,
    USDCTokenMintAddress: USDC_TOKEN_MINT_ADDRESS_DEVNET,
    SOLTokenMintAddress: SOL_TOKEN_MINT_ADDRESS_DEVNET,
    WETHTokenMintAddress: WETH_TOKEN_MINT_ADDRESS_MAINNET,
    WBTCTokenMintAddress: WBTC_TOKEN_MINT_ADDRESS_MAINNET
}

export const tokenAddressKeysMainNet = 
{
    DAITokenMintAddress: new PublicKey(DAI_TOKEN_MINT_ADDRESS_MAINNET),
    USDCTokenMintAddress: new PublicKey(USDC_TOKEN_MINT_ADDRESS_MAINNET),
    SOLTokenMintAddress: new PublicKey(SOL_TOKEN_MINT_ADDRESS_MAINNET),
    WETHTokenMintAddress: new PublicKey(WETH_TOKEN_MINT_ADDRESS_MAINNET),
    WBTCTokenMintAddress: new PublicKey(WBTC_TOKEN_MINT_ADDRESS_MAINNET)
}

export const tokenAddressKeysDevNet = 
{
    DAITokenMintAddress: new PublicKey(DAI_TOKEN_MINT_ADDRESS_MAINNET),
    USDCTokenMintAddress: new PublicKey(USDC_TOKEN_MINT_ADDRESS_DEVNET),
    SOLTokenMintAddress: new PublicKey(SOL_TOKEN_MINT_ADDRESS_DEVNET),
    WETHTokenMintAddress: new PublicKey(WETH_TOKEN_MINT_ADDRESS_MAINNET),
    WBTCTokenMintAddress: new PublicKey(WBTC_TOKEN_MINT_ADDRESS_MAINNET)
}